Test: Userモデルテスト完成
zskteam-20201211-1445/zsksample_rails01 pull request #18
Opened 2020-12-27 11:54 UTC by astouKen

close
https://github.com/zskteam-20201211-1445/zsksample_rails01/issues/6

## 概要
Userモデル更新、Userモデルテスト作成

## 修正内容の検証方法

`bundle exec rspec`の実行

## この修正が正しい理由

テストコマンドが正常に完了したことを確認

2020-12-27 12:02 UTC, kamada-maki approved these changes
LGTMです！

2020-12-28 02:43 UTC, takao-sone requested changes
すみません、ちょっと口出させてください。

皆様が慣れていないのは承知していますし、こういった間違いをするのはしょうがないと思っていることを前提として聞いてください。


@astouKen 
そもそも論として、自動コードチェック（CI）でOKが出ていないPRをレビュー依頼するのはいけないです。これでレビューOKもらってもCI通すために再度コード変更してレビューしてもらわなければいけないので二度手間です。

@kamada-maki 
こういったPRのレビュー依頼がきたら「チェック通ってからにしてください。」と跳ね返してください。これ見逃している時点でレビューできてないです。

このPRで指摘させていただきましたが、以前のPRでの同現象は見逃していたのでそこはご勘弁を😓


転職成功した際に現場でやらないよう気をつけていただければと思います👍

2020-12-28 03:28 UTC, astouKen reviewed
ご指摘ありがとうございます！
本PRで発生しているエラー内容は一度高倉で確認させていただきます。
修正完了次第、再度レビュー依頼を発行いたします。

2020-12-28 08:06 UTC, kamada-maki commented
ご指摘ありがとうございます。
今後は自動コードチェックの時点でエラーが出ていないか確認後PRすること、
レビューするときにもエラーが出ていないか確認することを意識したいと思います

2020-12-28 09:05 UTC, takao-sone approved these changes
@astouKen 

素早い対応ありがとうございます！
LGTM!!
（CIのチェックのみ確認なのでコードの方は別の方の承認もらってください）

2020-12-28 12:49 UTC, kamada-maki approved these changes
改めて確認させていただきました！LGTMです！

2020-12-28 12:58 UTC, mamoru02 approved these changes
お疲れ様です！LGTMです！

2020-12-28 13:03 UTC, merged